### ISSUE TITLE
Auto authenticate in strategy "facebook" 

### ISSUE THREAD

**Issue by huystart17** [feathersjs/authentication-client#56]
### Steps to reproduce
I just use the function
```javascript
const feathers = require('feathers/client');
const rest = require('feathers-rest/client');
const hooks = require('feathers-hooks');
const superagent = require('superagent');
//const fetch = require('node-fetch');

const auth = require('feathers-authentication-client');
// Connect to REST endpoints
const feathersClient = feathers();
feathersClient.configure(hooks())
              .configure(rest().superagent(superagent))
              .configure(auth({storage: localStorage}));
feathersClient.authenticate({
	strategy: "facebook"
})
```
I don't know why
I can get __feathers-jwt__(in cookie, and use for that jwt for other service that need authentication ) , but i am not connect to facebook or login to facebook(even in anonymous browser , no facebook account , no cookies,...) . 
I am use newest feathers-cli

**Comment by daffl** [comment]
OAuth authentication has been overhauled in Feathers v4 authentication. Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
