### ISSUE TITLE
OAuth strategy support

### ISSUE THREAD

**Issue by b0c1** [feathersjs/authentication-client#62]
### Steps to reproduce

Currently it lacks oauth stratehy support, you can't use 'local' or another way, because oauth MUST use ```application/x-www-form-urlencoded``` content type.

**Comment by b0c1** [comment]
Another problem the token name is "access_token" in the OAUTH 2.0. But the passport setJWT only try "accessToken"

**Comment by daffl** [comment]
OAuth authentication has been overhauled in Feathers v4 authentication. Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
