### ISSUE TITLE
clear cookie fail

### ISSUE THREAD

**Issue by joacub** [feathersjs/authentication-client#93]
in my case teh cookie only is removed in the main page if i stay in one nested page the cookie still .

```js
exports.clearCookie = function clearCookie (name) {

  if (typeof document !== 'undefined') {
    document.cookie = `${name}=;expires=Thu, 01 Jan 1970 00:00:01 GMT;`;
  }

  return null;
```

this code aparently is workin but document.cookie not modifie any thing

**Comment by daffl** [comment]
This seems odd, isn't this specific to the domain?

**Comment by joacub** [comment]
I don’t know what you want say but the case is this not work I put a code for my part in my app and clean the cookie becouse your code not remove the cookie, for me the problem is solved but maybe other people les have same problem and can’t see the solution

**Comment by phenrigomes** [comment]
I have the same problem with this code: 

```
if (typeof document !== 'undefined') {
    document.cookie = `${name}=;expires=Thu, 01 Jan 1970 00:00:01 GMT;`;
  }
```

But I could not find why. The issue can be replicated with these steps:

1 - Login: Create the cookie.
2 - Reload the web page;
3 - Logout. The cookie is not removed.

If I dont reload the page the cookie is removed normally.

**Comment by daffl** [comment]
Cookies are no longer used in Feathers v4 authentication. Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
